service: serverless-auth

plugins:
  - serverless-offline

# Configuration variables
custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs12.x
  profile: default
  region: us-east-1
  environment:
    JWT_SECRET: ${self:custom.secrets.jwtSecret}
functions:
  login:
    handler: functions/login.handler
    events:
      - http:
          path: login
          method: post
          cors: true
  authorize:
    handler: functions/authorize.handler
  getCats:
    handler: functions/getRecords.handler
    events:
      - http:
          path: getRecords
          method: get
          cors: true
          # authorizer: authorize # Retrieving records is public or we can make private
  putRecords:
    handler: functions/putRecords.handler
    events:
      - http:
          path: putRecords
          method: post
          cors: true
          authorizer: authorize # Modifying records is protected
